### ISSUE TITLE
Merging git-{commit,rebase}-mode and with-editor into Magit

### ISSUE THREAD

**Issue by tarsius** [magit/git-modes#117]
I intend to move `git-commit-mode`, `git-rebase-mode` and `with-editor` from `magit/git-modes` to `magit/magit`. That will be done in two steps (1) create a branch which removes all other files (2) merge that branch into Magit's `next` branch. Magit's history will then have two root commits.

When I decided to keep `git-commit-mode` inside `git-modes` and even move `magit-rebase-mode` there under its new name `git-rebase-mode` it wasn't obvious yet that the integration between Magit and `git-{commit,rebase}-mode` would increase as much as it did. A lot of that is done using the new library `with-editor` which deals with making the current Emacs instance usable as `$GIT_EDITOR` (which was previously done in Magit) and abstracts code previously duplicated in `git-commit-mode` and `git-rebase-mode`, and improves upon that.

Magit no longer just binds a few keys to commands from `git-{commit,rebase}-mode`. It is no longer possible to replace these libraries with equivalent third-party libraries (not that any suitable ones ever existed). Also they are mandatory now, not only would one lose major features if they were not present, Magit would not even compile without them.

The opposite is not true, `git-commit-mode` and `git-rebase-mode` work just fine without Magit, and I do not intend to change that. `with-editor` does not require Magit or these libraries, in fact it doesn't even care about Git itself.

So yes, it was a mistake to have these libraries in a separate repository but having made a mistake shouldn't keep us from fixing it. Doing so will make development easier and it will also make the bug reports stop, that are the result of users forgetting to update `git-modes` when updating `magit`. As more people switch to Magit's `next` branch when it enters the beta phase later this year, such invalid bug reports would rise to an annoying level.

---

I am also considering renaming `git-commit-mode.el` to `git-commit.el` and `git-rebase-mode.el` to `git-rebase.el`, as library names are not supposed to end with `-mode`. In the case of `git-commit-mode.el` keeping the old names would be especially strange because `git-commit-mode` now only plays a very marginal role, it's a minor-mode now which is only turned on for its keymap.

---

Finally I would like to change the copyright notice in the moved libraries to be like that of other libraries that are already part of `magit/magit` by applying this patch:

``` diff
diff --git a/git-commit-mode.el b/git-commit-mode.el
index 7a3dbb6..2ea5047 100644
--- a/git-commit-mode.el
+++ b/git-commit-mode.el
@@ -1,11 +1,13 @@
 ;;; git-commit-mode.el --- edit Git commit messages  -*- lexical-binding: t; -*-

-;; Copyright (c) 2010-2012  Florian Ragwitz
-;; Copyright (c) 2012-2013  Sebastian Wiesner
 ;; Copyright (C) 2010-2014  The Magit Project Developers
+;;
+;; For a full list of contributors, see the AUTHORS.md file
+;; at the top-level directory of this distribution and at
+;; https://raw.github.com/magit/magit/master/AUTHORS.md

 ;; Authors: Jonas Bernoulli <jonas@bernoul.li>
 ;;     Sebastian Wiesner <lunaryorn@gmail.com>
 ;;     Florian Ragwitz <rafl@debian.org>
 ;; Maintainer: Jonas Bernoulli <jonas@bernoul.li>
 ;; Homepage: https://github.com/magit/git-modes
```

@lunaryorn and @rafl, are you okay with that?

**Comment by ceyes** [comment]
Hello, I used `git-commit-mode` and `git-rebase-mode`for a long time, and just found it was removed:(

Now I have to install and study Magit, to get them back. But find there's no `git-commit-mode` when I evoking  emacs to edit comit message by `git commit`. (It works if evoked by `magit-status`, but I don't want to use git integrated in emacs, I really like previous lightweight usage).

I cannot find a command or configuration to achieve my simple requirement, could you help on that?

Thanks

**Comment by tarsius** [comment]
The successor of these package, `git-commit` and `git-rebase`, are indeed developed inside the Magit  repository. But `git-commit` is distributed as a separate Elpa package, so you can install that by itself. The same isn't true for `git-rebase`. Its integration with Magit is a bit tighter, so you have to install `magit` itself to get `git-rebase`. But that doesn't mean that you have to use Magit.


> Now I have to install and study Magit, to get them back. But find there's no `git-commit-mode` when I evoking  emacs to edit comit message by `git commit`. (It works if evoked by `magit-status`,

`git-commit-mode` no longer is a major-mode. This allows using an arbitrary major-mode when writing commit messages, i.e. `text-mode` or `markdown-mode`. See option `git-commit-major-mode`. You can even use a different major-mode in different repositories.

> I cannot find a command or configuration to achieve my simple requirement, could you help on that?

This should still work as before. You need to set and export the `GIT_EDITOR` variable in the shell. And in Emacs you need to load the `git-commit` library and start the server.

**Comment by ceyes** [comment]
Thanks for the explanation.
After loading `git-commit` and setting `GIT_EDITOR`, I can get `git-commit-mode` work, but still have 2 small problems:

1. Directly call emacs doesn't have `git-commit-mode`, but I can get it work with emacsclient
2. The `git-commit-mode` no longer support `C-c C-c` to finish a commit, nor `C-c C-k` to abort a commit. I checked git-commit.el and found there's no related functions and keybinds.

That really bring some inconsistent habit with previous `git-commit-mode` or `git-rebase-mode`.
It that because `git-commit-mode` no longer a major-mode, and works as new designed?

**Comment by tarsius** [comment]
> Directly call emacs doesn't have `git-commit-mode`, but I can get it work with emacsclient

I don't understand. But just in case: you obviously have to load the library before you can use it.

> The `git-commit-mode` no longer support `C-c C-c` to finish a commit, nor `C-c C-k` to abort a commit. I checked git-commit.el and found there's no related functions and keybinds.

Yes it does. The commands have different names because the functionality has been factored out into the new `with-editor` library. But these keys still do the same thing.

> That really bring some inconsistent habit with previous `git-commit-mode` or `git-rebase-mode`. It that because `git-commit-mode` no longer a major-mode, and works as new designed?

I think it's because you are having problems configuring it.

To verify that `git-commit` is really in use have a look at the mode-line it should contain `Text WE`.

**Comment by ceyes** [comment]
OK, my bad, seems ELPA just install required package but not auto load it.
After explicitly setting  `(require 'git-commit)`  in init.el, everything works well. And I can see `Text WE`  in the mode-line.

Thanks!
