### ISSUE TITLE
Transferring marmalade permissions

### ISSUE THREAD

**Issue by tarsius** [magit/git-modes#126]
@nicferrier could you please authorize me to upload:

* gitconfig-mode

Also please remove the permissions for anybody but me for:

* gitconfig-mode
* gitignore-mode
* magit

Thanks!

**Comment by tarsius** [comment]
@nicferrier I would still apprechiate if you could do this eventually.

Meanwhile, @lunaryorn, could you please upload https://github.com/magit/git-modes/releases/download/1.2.0/gitconfig-mode-1.2.0.el.

**Comment by lunaryorn** [comment]
@tarsius I would, but apparently I can't:

![bildschirmfoto 2015-07-02 um 08 42 09](https://cloud.githubusercontent.com/assets/224922/8471212/4492482a-2096-11e5-92d2-4d837ccb36ef.png)

**Comment by tarsius** [comment]
Indeed, your not actually the owner (not listed on https://marmalade-repo.org/profile/lunaryorn). Sorry about that.

I don't know how to figure out who has upload rights (short of lucking at every user profile). On https://marmalade-repo.org/packages/gitconfig-mode it only sais "by Sebastian Wiesner", but that is probably about the `Author` keyword in the library header.

**Comment by lunaryorn** [comment]
Never mind.  I probably uploaded it long ago, but that was still on the old Marmalade.  I don't care anymore, Marmalade is effectively dead now.  If you'd take my advice, focus in Melpa and Melpa Stable.

**Comment by tarsius** [comment]
Well, undead :-)

I do focus on Melpa! Unfortunately just supporting Marmalade without even focusing on that, requires like ~100 lines in the Makefiles, while supporting Melpa takes 0. :-(

Hopefully, Nic starts caring again soon. The main difference to me is that when something breaks on Melpa then it gets fixed in a day or two, while with Marmalade one can wait months without even a reply. But at least it is an "artifact store". (I don't really know what that means, but Nic has been bashing Melpa for not being one, so I am sure it's important.)

Ah, well. Focusing on other things is a good suggestion.

**Comment by lunaryorn** [comment]
Well then stop to support it 😃 It's not worth the effort anymore, is it?  Announce that you don't push to Marmalade anymore and call it a day.  If anyone complains let them do the nasty work for Marmalade 😄

**Comment by tarsius** [comment]
I am just not quite ready to let go yet :-)

**Comment by tarsius** [comment]
I can now upload this package. But there are still problems with other packages.
