### ISSUE TITLE
git-commit-abort saves COMMIT_EDITMSG

### ISSUE THREAD

**Issue by NimoTh** [magit/git-modes#127]
Not sure if this is the right place to report this. I have `emacs -nw` set as my editor in git config. Running `git commit` correctly opens emacs in-place in my gnome-terminal. When I press <kbd>C-c C-k</kbd> for kill, or when I invoke similar commands, such as `git-commit-abort`, the file `.git/COMMIT_EDITMSG` is written. That means, the commit actually goes ahead, which is not intended. 

Rather, I expect the content to be stored "somewhere", and is then accessible next time I invoke `git commit` from the same repository.

**Comment by tarsius** [comment]
You should use the `emacsclient` instead of `emacs`.

Git is told about aborts by using a non-zero exit status, but that is implemented in a way that only works when using the `emacsclient` as `GIT_EDITOR`. I doubt it is possible to have `emacs` intentionally exit with a non-zero exit stastus.

**Comment by npostavs** [comment]
> I doubt it is possible to have emacs intentionally exit with a non-zero exit stastus.

Not sure if it's practical for magit, but `kill-emacs` does this.

```
(kill-emacs &optional ARG)

Exit the Emacs job and kill it.
If ARG is an integer, return ARG as the exit program code.
...
```

**Comment by NimoTh** [comment]
emacsclient works fine for me. From my side, spending work on making the stand-alone emacs approach work is not worth the effort. Judging from Google and Stack Exchange, there are not too many use cases for emacs as a stand-alone git commit editor.
