### ISSUE TITLE
Wrong highlighting (gitconfig)

### ISSUE THREAD

**Issue by kornev** [magit/git-modes#132]
![default](https://cloud.githubusercontent.com/assets/5138477/16706075/c96eefe6-45af-11e6-8899-4e5281b40129.jpg)

**Comment by kyleam** [comment]
Sorry, I don't understand your comment.  I didn't say you shouldn't
use continued lines.  The commit that I pushed was intended to fix the
spurious highlighting that you reported.  Does it not?
