### ISSUE TITLE
Support other *ignore files within gitignore-mode

### ISSUE THREAD

**Issue by Fuco1** [magit/git-modes#139]
Most notably `.dockerignore` which uses virtually the same syntax.

Do you think it's a good idea to add these to auto-mode-alist for gitignore-mode?

**Comment by tarsius** [comment]
> Do you think it's a good idea to add these to auto-mode-alist for gitignore-mode?

No, I do not want to extend the scope of this package, and if we did, then we should change the name, which would inconvenient users who already use it. Besides, this is very little code so it can be easily be copy-pasted and adjusted as needed to create a new package.

If you do create a new package to deal with all sorts of *ignore* files, then you should probably also keep support for `.gitignore`.

If you don't want to maintain a new package yourself, then you can of course also just add to `auto-mode-alist` in your init file. As a compromise, you might want to add the necessary code snippets to this projects wiki (which is disabled at the moment, tell me if you intend to do so).

> which uses **virtually** the same syntax

That will lead to feature requests and me having to read the documentation of things I am not interested in.

**Comment by Fuco1** [comment]
> If you don't want to maintain a new package yourself, then you can of course also just add to auto-mode-alist in your init file.

This is what I've done and I'm happy with it.  Maybe a note in readme about this?  I don't think most people read the github wikis.

**Comment by tarsius** [comment]
Could you please create a pr doing that?
