### ISSUE TITLE
Installation steps for git-modes

### ISSUE THREAD

**Issue by HarrisonMc555** [magit/git-modes#140]
I've tried searching the website, this repository, StackExchange, etc. and haven't found any easy installation instructions. I'm guessing installation is intended to be "copy the files and load them in your `.emacs`". If that's the case, could we add a line saying so to the README? If there's another way (via Melpa or otherwise) then I'd love to hear about it, because I can't find anything.

I assumed this would be available either via Melpa (or another package repository) or included in `magit`, but I don't think either of those are true.

**Comment by tarsius** [comment]
Each of these libraries is available as a separate package on Melpa.

The library commentary of `git-modes.el` contains this information:

```
;; This package provides several major modes for editing Git
;; configuration files.  The modes are:

;;    `gitattributes-mode'
;;    `gitconfig-mode', and
;;    `gitignore-mode'

;; Each mode is defined in its own library by the same name.  Loading
;; `git-modes' causes all three libraries to be loaded, but you could
;; also load the libraries individually.  On Melpa, the libraries are
;; distributed as separate packages.
```

But I suppose I could add that information to the readme as well.

**Comment by HarrisonMc555** [comment]
Ah, that makes sense. I figured I was probably missing something like that.

Thank you for your quick reply and README update! :+1:
